#ifndef JSK_BOOT_MULTIBOOT_H
#define JSK_BOOT_MULTIBOOT_H

#include <stdint.h>

#include "JSK/BOOT/VBE.H"

typedef struct mb_aout_sym_table_t
{
        uint32_t tab_size;
        uint32_t str_size;
        uint32_t addr;
        uint32_t reserved;
} __attribute__ ((packed)) MultibootAOutSymTable;

typedef struct mb_elf_section_header_table_t
{
        uint32_t num;
        uint32_t size;
        uint32_t addr;
        uint32_t shndx;
} __attribute__ ((packed)) MultibootELFSectionHeaderTable;

typedef struct mb_module_t
{
        uint32_t mod_start;
        uint32_t mod_end;
        uint32_t str;
        uint32_t reserved;
} __attribute__ ((packed)) MultibootModule;

typedef struct mb_info_t
{
        uint32_t flags;
        uint32_t mem_lower;
        uint32_t mem_upper;
        uint32_t boot_device;

        uint32_t cmdline;
        uint32_t mods_count;
        uint32_t mods_addr;

        union
        {
                MultibootAOutSymTable aout_sym;
                MultibootELFSectionHeaderTable elf_sec;
        } u;

        uint32_t mmap_length;
        uint32_t mmap_addr;

        uint32_t drives_length;
        uint32_t drives_addr;

        uint32_t config_table;
        uint32_t boot_loader_name;

        uint32_t apm_table;

        uint32_t vbe_control_info;
        VbeModeInfo *vbe_mode_info;
        uint16_t vbe_mode;
        uint16_t vbe_interface_seg;
        uint16_t vbe_interface_off;
        uint16_t vbe_interface_len;
} __attribute__ ((packed)) MultibootInfo;

typedef struct mb_mmap_entry_t
{
        uint32_t size;
        uint32_t addr_low;
        uint32_t addr_high;
        uint32_t len_low;
        uint32_t len_high;
#define MULTIBOOT_MEMORY_AVAILABLE 1
#define MULTIBOOT_MEMORY_RESERVED 2
#define MULTIBOOT_MEMORY_ACPI_RECLAIMABLE 3
#define MULTIBOOT_MEMORY_NVS 4
#define MULTIBOOT_MEMORY_BADRAM 5
        uint32_t type;
} __attribute__ ((packed)) MultibootMMapEntry;

#endif
