CMAKE_MINIMUM_REQUIRED (VERSION 3.22)

SET (SOURCES
        CLASS.C
        MODULE.C
        HASH.C
        MSG.C
        STATICS.C
        CATEGORY.C
        PROTOCOL.C
        OBJECT.M
        PROTOCOL.M)

INCLUDE (${CMAKE_SOURCE_DIR}/CMAKE/FIXEXTS.CMAKE)

ADD_LIBRARY (OBJC_RUNTIME_OBJS
        OBJECT
        ${SOURCES})
