CMAKE_MINIMUM_REQUIRED (VERSION 3.20)

PROJECT (JSK 
        LANGUAGES
                C CXX ASM_NASM)

SET (CMAKE_C_STANDARD 90)

SET (INCLUDE_DIR ${CMAKE_SOURCE_DIR}/INCLUDE)
SET (BUILD_DIR   ${CMAKE_BINARY_DIR})
SET (KERNEL_BIN  ${BUILD_DIR}/KERNEL.BIN)
SET (BOOT_BIN    ${BUILD_DIR}/BOOT.BIN)
SET (IMAGE       ${BUILD_DIR}/JSK.IMG)

ADD_SUBDIRECTORY (GRAPHICS)
ADD_SUBDIRECTORY (KERNEL)
ADD_SUBDIRECTORY (BOOT)

#
# JSK.IMG
#
ADD_CUSTOM_COMMAND (
        OUTPUT ${IMAGE}

        COMMAND ${CMAKE_COMMAND} -E cat
                ${BOOT_BIN}
                ${KERNEL_BIN}
                > ${IMAGE}

        DEPENDS
                ${BOOT_BIN}
                ${KERNEL_BIN}

        VERBATIM)

ADD_CUSTOM_TARGET (JSK ALL
        DEPENDS ${IMAGE})

ADD_DEPENDENCIES (JSK
        BOOT
        KERNEL)
